;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-slash
	c-indent-line-or-region
	switch-to-buffer
	))

(setq mc/cmds-to-run-once
      '(
	indent-for-tab-command
	))
